syntax = "proto3";

package todo.v1;

import "google/protobuf/timestamp.proto";

message Todo {
  int64 id = 1;
  string title = 2;
  bool done = 3;
  bytes checksum = 4;
  google.protobuf.Timestamp created_at = 5;
}

message ListTodosRequest {
  int64 owner_id = 1;
}

message ListTodosResponse {
  repeated Todo todos = 1;
}

message CreateTodoRequest {
  string title = 1;
}

message CreateTodoResponse {
  Todo todo = 1;
}

service TodoService {
  rpc ListTodos(ListTodosRequest) returns (ListTodosResponse);
  rpc CreateTodo(CreateTodoRequest) returns (CreateTodoResponse);
}
